query organizationProfileComplete($filter: GenericFilterRequestOrganizationProfileCompleteInputType!) {
  organizationProfileComplete(filter: $filter) {
    listDto {
      items {
        id
        ngoLogo
        coverPhoto
        bio
        certificate
        profileDetails
        projects
        webSiteLinks
        completeProfilePercentage
        phoneNumber
      }
      count
    }
  }
}
