const linearIconNames = [
  'Youth',
  'youtube',
  'Women-Issues',
  'whatsapp',
  'vuejs',
  'vuejs-1',
  'Volume',
  'Volume-Up',
  'Voice',
  'vk',
  'vk-1',
  'visual-studio',
  'Video',
  'upper-arrow',
  'upload-image-438840-2452, gallery',
  'Unread-Notifications',
  'Unmute',
  'twitter',
  'twitter-1',
  'tumblr',
  'tumblr-2',
  'tumblr-1',
  'trash',
  'Today-Notifications',
  'timer',
  'tiktok',
  'tiktok-solid',
  'text',
  'telegram',
  'telegram-1',
  'swiggy',
  'Support',
  'stopwatch, Clock',
  'Stop',
  'start',
  'star',
  'Sport',
  'Specific-followers',
  'Sort2',
  'Sort',
  'social-network',
  'social-media',
  'social-media-3',
  'social-media-2',
  'social-media-1',
  'Snippet',
  'snapchat',
  'snapchat-2',
  'snapchat-1',
  'slack',
  'slack-1',
  'skype',
  'skype-1',
  'Show-all-Notifications',
  'Share',
  'Setting',
  'Setting-1',
  'Send',
  'secure, protected, safe, antivirus, protect, shield, private',
  'Science--Technology',
  'Saved',
  'Save',
  'Save-Changes',
  'right-arrow',
  'right-arrow-1',
  'right-arrow1, Continue',
  'Reshare',
  'Research-and-Public-Policy',
  'Report',
  'reply',
  'Remove',
  'remove-image, remove-photo',
  'remove-account, Unfollow',
  'Reload',
  'Religion',
  'Relationship',
  'Refugee-Issues',
  'Read-Notifications',
  'react',
  'raddit',
  'px',
  'public',
  'profile',
  'Profile-Photo',
  'Professional-Association',
  'Premium',
  'Poverty-Alleviation',
  'Plus',
  'play',
  'pinterest',
  'pinterest-solid',
  'Pin',
  'Pencil, Edit-Pen',
  'paypal',
  'pause-button',
  'Part-time',
  'Page-Collection',
  'opera',
  'opera-1',
  'Only-me',
  'office-bag',
  'Occupation',
  'Number-list-format',
  'Notifications-Category',
  'notes',
  'No-Sound',
  'NGO',
  'NFT',
  'National-Minorities',
  'National-Heritage',
  'Mute',
  'music',
  'multiple-image',
  'mortarboard, Education',
  'money, Coin',
  'mobile',
  'Minus',
  'Mic',
  'Mic-mute',
  'message',
  'medium',
  'master-card',
  'Mass-Media',
  'lock, pad-lock, safe1, security, protected1, lock-alt',
  'lock-open, pad-lock1, access, unlock, Solid',
  'location',
  'location-pin',
  'Loading',
  'list-format',
  'linkedin',
  'linkedin-1',
  'line',
  'line-symbol',
  'Like, thumbs-up',
  'left-arrow',
  'left-arrow-1',
  'Leave-Group',
  'label',
  'Joined-Garden-of-Love, Calendar',
  'java-script',
  'International',
  'International-Relation',
  'intercom',
  'intercom-1',
  'instagram',
  'instagram-1',
  'Info',
  'impression',
  'image',
  'Image-Position',
  'Image-Position-4',
  'Image-Position-3',
  'Image-Position-2',
  'Image-Position-1',
  'Humanitarian-Assitance',
  'Human-Services',
  'Human-Right',
  'html',
  'html-1',
  'Hometown',
  'Home',
  'heart',
  'Health, Medical-problems',
  'Hashtag',
  'happy, happy-face, smiley, emoji, smile, ',
  'Handicapped-Issues',
  'Groups',
  'google',
  'google-play',
  'google-hangouts',
  'google-hangouts-alt',
  'google-drive',
  'github',
  'github-1',
  'GIF',
  'Full-Time',
  'Friends-except',
  'Freelancer',
  'forward',
  'Flag',
  'Filters',
  'Filter-Posts',
  'facebook',
  'facebook-1',
  'facebook-messenger',
  'facebook-messenger-1',
  'Eye',
  'Eye-Hidden',
  'Exclamation-Mark',
  'Environmental-Protection',
  'engagement-percent',
  'Education1',
  'Edit',
  'edit-message',
  'Economic-Development',
  'Earth',
  'Earlier-Notifications',
  'dropbox',
  'dribbble',
  'down-arrow',
  'dollar-coin',
  'Dislike',
  'Disaster-Relief',
  'descending',
  'cover-photo',
  'Connections',
  'company-logo',
  'Company-Logo-Empty',
  'Company-industry',
  'Community',
  'Community-Development',
  'comment',
  'Close',
  'Close-1',
  'clock, History',
  'City',
  'Children, Family-issue',
  'chat',
  'Catrgories',
  'Campaign',
  'camera-change, Rotate-Camera, Change-Image',
  'calendar',
  'BuyNFT',
  'Building, Company',
  'blogger',
  'blogger-1',
  'Block',
  'block, forbidden, forbidden-sign, prohibited, prohibited-sign, restricted, restricted-sign, ban, 1',
  'black-berry',
  'bitcoin',
  'bitcoin-1',
  'Birthday',
  'Bell',
  'behance',
  'behance-1',
  'Bag-Buy',
  'Auto-Flash, Flash',
  'Attach',
  'ascending',
  'Arts-and-culture',
  'Approve, Tick',
  'ApproveTick',
  'approve-user, All-Followers-Except',
  'apple',
  'apple-1',
  'Animals',
  'android',
  'android-1',
  'amazon',
  'Agriculture',
  'Advertise',
  'adobe',
  'adobe-1',
  'Admin',
  'add-photo, camera',
  'Add-New',
  'add-chat',
  'add-account, add-user',
  'account',
  'account-info, user-info',
  '2',
] as const;

const solidIconNames = [
  'Youth',
  'Women-Issues',
  'Volume',
  'Volume-Up',
  'video',
  'upload-image-438840-2452, gallery',
  'Unread-Notifications',
  'Unmute',
  'underline',
  'trash',
  'Today-Notifications',
  'timer',
  'text',
  'tag',
  'Support',
  'stopwatch, Clock',
  'Stop',
  'start',
  'star',
  'Sport',
  'Specific-followers',
  'Show-all-Notifications',
  'shield, question, protected, secure, safe, shield-question',
  'Share',
  'Setting',
  'Send',
  'secure1, protected1, safe1, antivirus, protect, shield1, private',
  'Science--Technology',
  'Saved',
  'Save',
  'Save-Changes',
  'Reshare',
  'Research',
  'Research-and-Public-Policy',
  'Report',
  'reply',
  'remove-image, remove-photo',
  'remove-account, Unfollow',
  'Religion',
  'Relationship',
  'Refugee-Issues',
  'Read-Notifications',
  'Quote',
  'public',
  'profile-Solid',
  'Profile-Photo',
  'Professional-Association',
  'Premium',
  'Poverty-Alleviation',
  'Porfile-badge',
  'play',
  'Pin',
  'Pencil, Edit-Pen',
  'pause-button',
  'Part-time',
  'Page-Collection',
  'Only-me',
  'office-bag',
  'Occupation',
  'Notifications-Category',
  'notes-Solid',
  'No-Sound',
  'NGO',
  'NFT',
  'National-Minorities',
  'National-Heritage',
  'Mute',
  'music',
  'multiple-image-Solid',
  'mortarboard, Education',
  'money, Coin',
  'mobile',
  'Minus-Solid',
  'Mic',
  'Mic-Mute-Solid',
  'message',
  'Menu',
  'Menu-1',
  'Mass-Media',
  'lock, pad-lock, safe2, security, protected2, lock-alt',
  'lock-open, pad-lock1, access, unlock, Solid',
  'location',
  'location-pin',
  'Link',
  'line-symbol',
  'Like, thumbs-up',
  'Leave-Group',
  'Joined-Garden-of-Love, Calendar',
  'italic',
  'International',
  'International-Relation',
  'Info',
  'image',
  'Image-Position',
  'Image-Position-4',
  'Image-Position-3',
  'Image-Position-2',
  'Image-Position-1',
  'Hyperlink',
  'Humanitarian-Assitance',
  'Human-Services',
  'Human-Right',
  'Hometown',
  'Home',
  'heart',
  'Health, Medical-problems',
  'happy, happy-face, smiley, emoji, smile',
  'Handicapped-Issues',
  'Groups',
  'GIF',
  'Full-Time',
  'Friends-except',
  'Freelancer',
  'forward',
  'Flag',
  'Filters',
  'Filter-Posts',
  'Eye',
  'Eye-Hidden',
  'Exclamation-Mark',
  'Exclamation-Mark-1',
  'Environmental-Protection',
  'Education1',
  'Edit',
  'edit-message',
  'Economic-Development',
  'Earth',
  'Earlier-Notifications',
  'dollar-coin',
  'Dislike',
  'Disaster-Relief',
  'cover-photo',
  'Connections',
  'Company-industry',
  'Community',
  'Community-Development',
  'comment',
  'Close',
  'clock, History',
  'City',
  'Children, Family-issues',
  'chat',
  'Catrgories',
  'Campaign',
  'camera-change, Rotate-Camera, Change-Image',
  'calender',
  'BuyNFT',
  'Building, Company',
  'bold',
  'Block',
  'Birthday',
  'Bell',
  'Bag-Buy',
  'Auto-Flash, Flash',
  'Arts-and-culture',
  'Approve, Tick',
  'approve-user, All-Followers-Except',
  'Animals',
  'Agriculture',
  'Advertise',
  'Admin',
  'add-photo-solid, camera',
  'Add-New',
  'add-chat',
  'add-account, add-user',
  'account-Solid',
  'account-info, user-info',
] as const;

export type SolidIconType = typeof solidIconNames[number];
export type LinearIconType = typeof linearIconNames[number];
