apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: {{ service_name }}
  name: {{ service_name }}
spec:
  type: NodePort
  ports:
    - name: "{{ port_number }}" 
      port: {{ port_number }}
      targetPort: 3000
  selector:
    app: {{ service_name }}

