overwrite: true
schema: ${NEXT_PUBLIC_GQL_HISTORY_SCHEMA}
hooks:
  afterAllFileWrite:
    - node scripts/make-api-reducers.js --service=HISTORY
generates:
  src/:
    hooks:
      afterOneFileWrite:
        # - eslint --fix
    preset: near-operation-file
    documents: src/_requests/graphql/history/**/*.gql
    presetConfig:
      extension: .generated.ts
      baseTypesPath: '@types/sections/serverTypes.ts'
      importTypesNamespace: ServerTypes
    plugins:
      - typescript-operations
      - typescript-rtk-query:
          importBaseApiFrom: src/_clients/graphql/History
    config:
      addDocBlocks: false
      exportFragmentSpreadSubTypes: true
      exportHooks: true
      skipTypename: true
      useTypeImports: true
