overwrite: true
schema: ${NEXT_PUBLIC_GQL_SEARCH_SCHEMA}
hooks:
  afterAllFileWrite:
    - node scripts/make-api-reducers.js --service=SEARCH
generates:
  src/:
    hooks:
      afterOneFileWrite:
        # - eslint --fix
    preset: near-operation-file
    documents: src/_requests/graphql/search/**/*.gql
    presetConfig:
      extension: .generated.ts
      baseTypesPath: '@types/sections/serverTypes.ts'
      importTypesNamespace: ServerTypes
    plugins:
      - typescript-operations
      - typescript-rtk-query:
          importBaseApiFrom: src/_clients/graphql/Search
    config:
      addDocBlocks: false
      exportFragmentSpreadSubTypes: true
      exportHooks: true
      skipTypename: true
      useTypeImports: true
